spring.application.name=climaAlert
spring.docker.compose.enabled=false
weatherapi.key=${WEATHER_API_KEY:}
email.emisor=${EMAIL_EMISOR:mimail@mail.com}
email.destinatarios=${EMAIL_DESTINATARIOS:destion@mail.com}
sendgrid.api-key=${SENDGRID_API_KEY:}
